Домашняя работа 4
khitao/TinkoffFirstHW pull request #7
Opened 2023-10-08 12:57 UTC by khitao

Добавлен сервис WeatherApiService.

Реализована конфигурация RateLimiter.

Создан WebClient для работы с Weather API.

Реализован WeatherApiController для обработки запросов к /weather_api/current.

Добавлены модели данных для парсинга ответа от API.

Реализована обработка исключений API.

Обновлен openapi.yml.

2023-10-09 22:03 UTC, madoed requested changes
Нужно доработать по комментариям

2023-10-09 22:03 UTC, madoed commented on SpringBootApp/build.gradle
> +    implementation 'io.github.resilience4j:resilience4j-reactor:1.7.0'
Зависимости для spring-boot-2, но выше spring-boot-3

Соотвественно не будет работать ratelimiter

2023-10-09 22:03 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/config/WeatherApiConfig.java
> +    public WebClient webClient() {
Лучше назвать bean более говоряще, типа weatherApiClient

2023-10-09 22:03 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/model/Condition.java
> +public class Condition {
Можно использовать record вместо связки class + @Date

2023-10-09 22:03 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/model/Location.java
> +    private String localtime;
Можно сразу указывать нужный java.time класс с аннотацией JsonFormat

2023-10-09 22:03 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/service/WeatherApiService.java
> +    WebClient webClient;
а почему default модификатор доступа?

2023-10-09 22:03 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/service/WeatherApiService.java
> +        }
Можно спрятать за аннотацией `@RateLimiter`

2023-10-09 22:03 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/service/WeatherApiService.java
> +                ObjectMapper objectMapper = new ObjectMapper();
На каждую ошибку будет создаваться свой ObjectMapper - слишком затратно, надо вынести бином в конфигурацию

2023-10-09 22:03 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/service/WeatherApiService.java
> +        }
Выглядит нечитабельно, нужно выделить в отдельный метод/класс на выбор

Ещё почитать про ErrorHandling https://www.baeldung.com/spring-webflux-errors

2023-10-10 01:40 UTC, khitao commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/model/Location.java
> +    private String localtime;
@JsonFormat(pattern = "yyyy-MM-dd HH:mm")
        LocalDateTime localtime  

Постоянно вылетают такие ошибки JSON decoding error: Cannot deserialize value of type `java.time.LocalDateTime` from String "2023-10-10 4:38": Failed to deserialize java.time.LocalDateTime: (java.time.format.DateTimeParseException) Text '2023-10-10 4:38' could not be parsed at index 11

2023-10-10 01:41 UTC, khitao commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/service/WeatherApiService.java
> +        }
Что то у меня не получается использовать эту аннотацию. Не понимаю, что не так делаю зависимости обновил.(

2023-10-10 14:32 UTC, khitao commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/service/WeatherApiService.java
> +        }
Не получается 😩. @RateLimiter(name = "weatherApi") не работает. Он почему-то не видит настройки моего Бина в конфигурации и выдает какие-то свои дефолтные ограничения: 2023-10-10T16:52:16.604+03:00 DEBUG 37325 --- [nio-8080-exec-1] i.g.r.s.r.configure.RateLimiterAspect    : Created or retrieved rate limiter 'weatherApi' with period: 'PT0.0000005S'; limit for period: '50'; timeout: 'PT5S'; method: 'ru.khodov.springbootapp.service.WeatherApiService#getCurrentWeather'. Но если в properties прописываю ограничения он их видит.

2023-10-10 16:34 UTC, khitao commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/model/Location.java
> +    private String localtime;
Хотя вот, что в документации написано 
![Документ](https://i.imgur.com/l7UfiBd.png)

2023-10-10 19:32 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/model/Location.java
> +    private String localtime;
Попробуй добавить этот модуль https://fasterxml.github.io/jackson-modules-java8/javadoc/datetime/2.9/com/fasterxml/jackson/datatype/jsr310/JavaTimeModule.html

2023-10-10 19:42 UTC, madoed approved these changes
Доработай комментарии, задачу зачитываю

2023-10-10 19:42 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/controllers/WeatherApiController.java
> +    public Mono<ResponseEntity<WeatherApi>> getCurrentWeather(@PathVariable String location) {
Зачем Mono и ResponseEntity? 
Можно просто оставить Mono<WeatherApi> или просто WeatherApi, сделав на сервисном уровне .block объекту Mono

2023-10-10 22:16 UTC, merged