Домашняя работа 5
khitao/TinkoffFirstHW pull request #8
Opened 2023-10-15 17:48 UTC by khitao

Запустил локальную БД H2. Описал структуру сущностей City, CityWeather, WeatherType в скриптах Liquibase (schema.sql).

Реализовал CRUD-операции в соответствующих репозиториях для каждой модели, используя JDBC и Hibernate.

Обновил openapi.yml

2023-10-16 09:18 UTC, madoed requested changes

2023-10-16 09:18 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/model/City.java
> +public class City {
Для Entity должен присутствовать  конструктор без аргументов

2023-10-16 09:18 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/model/CityWeather.java
> +public class CityWeather {
Для Entity должен присутствовать конструктор без аргументов

2023-10-16 09:18 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/model/WeatherType.java
> +public class WeatherType {
Для Entity должен присутствовать конструктор без аргументов

2023-10-16 09:18 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/model/WeatherType.java
> +
Зачем столько пустых строк?

2023-10-16 09:18 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/repositories/CityJdbcRepository.java
> +        return jdbcTemplate.query("SELECT * FROM city", new BeanPropertyRowMapper<>(City.class));
BeanPropertyRowMapper необходимо использовать с осторожностью. Но в случае 2ух полей подойдет.

Но я все же предложил написать свою реализацию RowMapper под City

2023-10-16 09:18 UTC, madoed commented on SpringBootApp/src/main/resources/schema.sql
> +       (3, 3, -5.0, '2023-10-14 12:00:00');
В задании сказано использовать инструмент миграции Liquibase

Необходимо переделать

2023-10-16 09:18 UTC, madoed commented on SpringBootApp/build.gradle
> +}
Зачем?

2023-10-16 09:18 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/model/CityWeather.java
> +    @ManyToOne()
Пустые скобки не нужны

2023-10-16 09:18 UTC, madoed commented on SpringBootApp/src/main/java/ru/khodov/springbootapp/repositories/CityWeatherJdbcRepository.java
> +                "LEFT JOIN weather_type wt ON cw.weather_type_id = wt.id";
Можно использовать text blocks https://www.baeldung.com/java-text-blocks

2023-10-16 14:02 UTC, khitao commented on SpringBootApp/build.gradle
> +}
IDEA рекомендовала добавить, так как в проекте был устаревший метод. Забыл убрать после внесения изменений

2023-10-17 11:25 UTC, madoed approved these changes

2023-10-22 12:13 UTC, merged